name: Construir y Publicar Imágenes en Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "frontend", "backend" ]  # construimos dos imágenes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile   # <--- si tu frontend quedó con 'DockerFile', cambia esta línea más abajo
          push: true
          # platforms: linux/amd64,linux/arm64   # opcional multi-arch
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ matrix.service }}-demo:latest
            ${{ secrets.DOCKER_USER }}/${{ matrix.service }}-demo:${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ matrix.service }}-demo:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ matrix.service }}-demo:buildcache,mode=max
